### ISSUE TITLE
Unexpected env "NVIDIA_**" in YAML

### ISSUE THREAD

**Issue by Yancey1989** [couler-proj/couler#102]
After running a simple Couler program, the generated Argo YAML always contains the `NVIDIA_*` envs just like:
``` yaml
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: ""
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: ""
```

Why these variables and how can I remove the unexpected environment variables in specs?
