### ISSUE TITLE
The invalid step name: `<stdin>-`

### ISSUE THREAD

**Issue by Yancey1989** [couler-proj/couler#103]
When I run the Couler program by command 
``` bash
cat run.py | python -u
```

the generated workflow YAML contains the invalid step name `<stdin>-`:

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sqlflow
spec:
  entrypoint: sqlflow
  templates:
    - name: sqlflow
      steps:
        - - name: <stdin>-56-56
            template: <stdin>-56
        - - name: <stdin>-72-72
            template: <stdin>-72
```

Maybe we can use the workflow name as the step name prefix?
