### ISSUE TITLE
No insecure option for S3Artifact

### ISSUE THREAD

**Issue by sifat007** [couler-proj/couler#254]
# Summary

Ability to add `insecure:true` field to the S3 artifacts

```
...
inputs:
      artifacts:
        - name: my-input-artifact
          path: /my-input-artifact
          s3:
            endpoint: minio.argo.svc:9000
            insecure: true        <---------------------- Currently not possible from Couler
            bucket: foo
            key: coinflip-artifact.tgz
            accessKeySecret:
              name: minio-secrets
              key: accessKey
            secretKeySecret:
              name: minio-secrets
              key: secretKey
...
```

# Use Cases

Running local minio without HTTPS

Any recommendation for workarounds?

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
