### ISSUE TITLE
How to create new volume to share state between container runs?

### ISSUE THREAD

**Issue by Seanny123** [couler-proj/couler#62]
When writing an Argo workflow using YAML, it is possible to defined an `initContainer` step. For example, initializing working directories:
```yaml
initContainers:
    - name: mkdir
        image: alpine:latest
        command: ["mkdir", "-p", "/workdir/protocols/{{inputs.parameters.protocol}}"]
        mirrorVolumeMounts: true
    - name: chmod
        image: alpine:latest
        command: ["chmod", "-R", "a+rwX", "/workdir"]
        mirrorVolumeMounts: true
```

By using `mirrorVolumeMounts: true` we can share state between the containers using local storage. For example, the next step could be running a command:

```yaml
container:
    imagePullPolicy: Always
    image: "{{workflow.parameters.docker-image}}"
    command:
        - fancy_script
    volumeMounts:
        - name: workdir
        mountPath: /workdir
```

Although it is possible to mount a volume with Couler:
```python
volume = Volume("workdir", "my-existing-volume")
volume_mount = VolumeMount("workdir", "/mnt/vol")
couler.add_volume(volume)
couler.run_container(
    image="docker/whalesay:latest",
    args=["echo -n hello world"],
    command=["bash", "-c"],
    step_name="A",
    volume_mounts=[volume_mount],
)
```

How does one create a new volume?

**Comment by terrytangyuan** [comment]
Great question! Creating new volume is not part of Couler's API yet as we haven't come across such a use case. In our use cases, system or DevOp engineers are usually responsible to create new volumes in advance and then analysts/data scientists can use the already created volumes. 

Alternatively, one can create new volumes using k8s Python SDK directly or use `couler.run_job(manifest)` to create a k8s resource as part of the workflow. Would this work for you? If not, feel free to propose a better way of doing this and then send a PR to add that functionality.

**Comment by Seanny123** [comment]
Turns out this question originates from a misunderstanding. The code provided _does not_ create a new volume. The new volume is actually specified as part of the manifest section of the Argo workflow:
```yaml
spec:
  serviceAccountName: argo
  imagePullSecrets:
    - name: docker-hub
  hostNetwork: true
  podDisruptionBudget:
    minAvailable: 99999
  volumes:
    - name: workdir
      emptyDir: {}
```

Those components of the workflow are creating the directories, but that's possible to do with `couler.run_script()`.  What's uniquely being defined in the Argo workflow is that these scripts should run in the same K8S pod. This is outside of the scope of this issue and probably outside of the scope of `couler`.
